### ISSUE TITLE
Planning: Front-End tasks

### ISSUE THREAD

**Issue by FernVR** [FernVR/pp5-repo#1]
## Tasks
- [x] Finalise colour scheme, typography and site name. - Ensure colour scheme meets accessibility guidelines.
- [x] Organise image folder - ensure img sizing is correct.
- [x] Generate wireframes using Figma. Include wireframes for these pages:
    - [x] Home page
    - [x] Bookshop page
    - [x] Customer service page
    - [x] Register/Login pages
   -  [x] 404 error page
- [x] Generate logo and favicon and include in desktop project files.

### Additional Notes:
None
