### ISSUE TITLE
Product Admin

### ISSUE THREAD

**Issue by FernVR** [FernVR/pp5-repo#18]
As a **site administrator**, I can **access the product admin panel of the site** so that **I can edit, add or delete items for sale**.

### Acceptance Criteria
- Product Admin nav-link and page are only visible to admin users. 
- Products are available to view with a form to edit their fields.
- Admin users can create and delete items.

### Tasks
- [ ] Create product admin view, urls and template. - Test functionality
- [ ] Create search bar functionality.
- [ ] Paginated list of all products A-Z.
- [ ] Create filtering functionality. - refer to walkthrough project.
- [ ] Add edit product functionality.
    - [ ] edit all fields - name, description, rating, price + 'save changes' button
    - [ ] add button to upload img files to replace the image 
- [ ] Add create and delete product functionality.
- [ ] Test deployed version to ensure it matches development version.

### Additional Notes:
add any notes here
