### ISSUE TITLE
Planning: Features list

### ISSUE THREAD

**Issue by FernVR** [FernVR/pp5-repo#2]
## Tasks
- [x] Create list/spreadsheet of all features to be included.
- [x] Take note of all mandatory features from the assessment criteria.
- [x] Take note of all "might have" features that might not be included in the final project.
- [x] Decide on the order of which we will add each feature, depending on importance.

### Additional Notes:
None
