### ISSUE TITLE
Customer Support Page

### ISSUE THREAD

**Issue by FernVR** [FernVR/pp5-repo#21]
As a **user**, I can **easily access the customer support page** so that **I can give feedback and easily communicate any issues to the business admin**.

As a **site admin**, I can **easily access the customer support database on the admin panel** so that **I can receive feedback and easily communicate with customers regarding their issues**.

### Acceptance Criteria
- All users can access the customer support page through the link in the nav bar.
- Users can submit a feedback form with any queries or issues they might have.
- Admin users can access the form submissions from the admin panel.

### Tasks
- [x] Create customer support app, models, views, urls and template. Test functionality.
- [x] Add customer support form to the template.
- [x] Run server and submit a form, check if form information has been received in correct section of admin panel.
- [x] Test deployed version.

### Additional Notes:
add any notes here
