### ISSUE TITLE
Newsletter Form

### ISSUE THREAD

**Issue by FernVR** [FernVR/pp5-repo#26]
As a **user**, I can **subscribe to the business newsletter** so that **I can receive any news about offers or discounts via email**.

### Acceptance Criteria
- All users can access the form in the footer to subscribe to the newsletter.

### Tasks
- [ ] Add newsletter form to the footer. - refer to wireframe
- [ ] Use mail-chimp to create email subscribe functionality.
- [ ] run server and submit an email address to the form to test functionality.
- [ ] test deployed version

### Additional Notes:
Refer to relevant notes for anymore info.
