### ISSUE TITLE
Planning: Database Models

### ISSUE THREAD

**Issue by FernVR** [FernVR/pp5-repo#3]
## Tasks
- [x] Plan all database models from each app within a list.
- [x] Create an ERD of the database models using Lucid Chart.
- [x] Ensure there are 3 original custom models included, make note of the custom models.
- [x] Add sell book form to ERD map. 

### Additional Notes:
Can't edit my erd another time on lucid chart using the free version - maybe transfer whole erd to another platform to include all models .
