### ISSUE TITLE
Initial Installation

### ISSUE THREAD

**Issue by FernVR** [FernVR/pp5-repo#4]
### Acceptance Criteria
- Install initial programs required.
- Hide all sensitive information within hidden env file.

### Tasks
- [x] Create workspace.
- [x] Install : django, dj-database, psycopg2, gunicorn, cloudinary
- [x] Create env file and include secret key.
- [x] Include development server within ALLOWED HOSTS variable within settings.py

### Additional Notes:
Might not install cloudinary right away.
