### ISSUE TITLE
Create Project and Home page app

### ISSUE THREAD

**Issue by FernVR** [FernVR/pp5-repo#5]
As a **developer**, I can **create django project and home page app**, so that **I can test initial functionality**.

### Acceptance Criteria
- Home page view should return a message to the page.

### Tasks
- [x] Create django project in app directly and add any settings required.
- [x] Create home app, urls and initial view.
- [x] View to return http response with a message.
- [x] Run server and test functionality.

### Additional Notes:
add any notes here
