### ISSUE TITLE
Admin special credentials

### ISSUE THREAD

**Issue by FernVR** [FernVR/pp5-repo#6]
As a **site admin**, I can **access the admin panel using my admin login credentials** so that **I can access site databases and perform site admin tasks**.

### Acceptance Criteria
- Site admin should be able to access admin panel using their login info.

### Tasks
- [x] Create superuser in the terminal.
- [x] Make note of superuser credentials within project notes. Keep this information a secret.
- [x] Run server to login and test functionality.

### Additional Notes:
add any notes here
